### ISSUE TITLE
not finding once file on groupby

### ISSUE THREAD

**Issue by RGunning** [njgit/App-Pipeline-Lite#27]
I hit an error whilst running a groupby step

the groupby step grabs a file from a .once command

If I then run again specifying the job, the wrong job folder is searched.

i.e. file is in job 0

**Comment by RGunning** [comment]
recent update now has plite looking for a .once file in each of the jobs

i.e job0 looks in job0 folder, job1 looks in job1 folder, etc.

therefore no longer working

**Comment by njgit** [comment]
just to check  - is this an exe that you created from most recent code - or the one available in this repo?

**Comment by RGunning** [comment]
exe in the most recent repo.
(my PATH points at the unpacked version)

**Comment by njgit** [comment]
So just to be clear -  in your groupby step you are referring to a file produced in a step that has just been run once (.once) and instead of looking at job0 for all the groups it's looking at other jobs?

**Comment by RGunning** [comment]
yes

    macscollate.once
	cat [% jobs.macsmergedbroad.var %] > [% macscollate.var %] || true;
    calldiff.groupby.comp
	source [% macscollate.var %];

it then tried sourcing job0/macscollate/var in job 0
				 job1/macscollate/var in job1
				etc.

**Comment by njgit** [comment]
ok will work on a fix,  I think the commit that introduced this was done after the packed exe, so things should still work with that

**Comment by nw11** [comment]
fixed on branch https://github.com/njgit/App-Pipeline-Lite/tree/fix-groupby-with-once will merge to master soon

**Comment by nw11** [comment]
merged into master

**Comment by RGunning** [comment]
There is still an error in the groupby, it now won't accept input

An error occurred, check logs: Placeholder input.mm10.len in step macsmergedbroad references a normal step (input is not a .once or .groupby step) and is inconsistent with

**Comment by njgit** [comment]
Should work, let me know if there is something else

**Comment by RGunning** [comment]
looks good
