### ISSUE TITLE
Symlink Issue

### ISSUE THREAD

**Issue by RGunning** [njgit/App-Pipeline-Lite#6]
Found a minor issue with symlink

if running symlink on a groupby step, Name of datasource is repeated for each job in group.

e.g.

    /lustre/scratch110/sanger/rg12/Pipeline$ plite symlink -f Mark -r 6 -s createhubgroup#out /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/;

Output

    SYMLINK /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job1/createhubgroup/out /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/symlink/createhubgroup/6/27M-27M-27M-27M-27M-27M-27M-27M-out
    SYMLINK /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job0/createhubgroup/out /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/symlink/createhubgroup/6/27ac-27ac-27ac-27ac-27ac-27ac-27ac-27ac-out

**Comment by RGunning** [comment]
It also seems to get the name wrong

    rg12@web-bfint:~/ftp_folder/ChIPseq/symlink/createhubgroup/6/6$ more 27ac-27ac-27ac-27ac-27ac-27ac-27ac-27ac-out 
    createtrack.pl --vocab_url 'ftp://ngs.sanger.ac.uk/scratch/project/rg12/bp-vocab-2910141000.json' --sexes 'F M F M F M F M' --strain 'BL6 BL6 CAST CAST BL6 BL6 CAST CAST' --cell_types 'B B B B T T T T' --hmark '27M 27M 27M 27M 27M 27M 27M 27M' --replicate 'a a a a a a a a' --peak '/lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job8/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job9/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job10/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job11/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job12/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job13/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job14/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job15/macsunmerged/output8' --url_names 'BF_B_27M-narrowout BM_B_27M-narrowout CF_B_27M-narrowout CM_B_27M-narrowout BF_T_27M-narrowout BM_T_27M-narrowout CF_T_27M-narrowout CM_T_27M-narrowout' --type 'hammock' --base_url 'ftp://ngs.sanger.ac.uk/scratch/project/rg12/ChIPseq/symlink/macsunmerged/6' --url_suffix '.gz'
    rg12@web-bfint:~/ftp_folder/ChIPseq/symlink/createhubgroup/6/6$ more 27M-27M-27M-27M-27M-27M-27M-27M-out 
    createtrack.pl --vocab_url 'ftp://ngs.sanger.ac.uk/scratch/project/rg12/bp-vocab-2910141000.json' --sexes 'F M F M F M F M' --strain 'BL6 BL6 CAST CAST BL6 BL6 CAST CAST' --cell_types 'B B B B T T T T' --hmark '27ac 27ac 27ac 27ac 27ac 27ac 27ac 27ac' --replicate 'a a a a a a a a' --peak '/lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job0/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job1/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job2/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job3/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job4/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job5/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job6/macsunmerged/output8 /lustre/scratch110/sanger/rg12/Pipeline/ChIPseq/output/run6/job7/macsunmerged/output8' --url_names 'BF_B_27ac-narrowout BM_B_27ac-narrowout CF_B_27ac-narrowout CM_B_27ac-narrowout BF_T_27ac-narrowout BM_T_27ac-narrowout CF_T_27ac-narrowout CM_T_27ac-narrowout' --type 'hammock' --base_url 'ftp://ngs.sanger.ac.uk/scratch/project/rg12/ChIPseq/symlink/macsunmerged/6' --url_suffix '.gz'


Here I am having the Mark in the name not matching up to the mark in the file

**Comment by nw11** [comment]
thanks, this should fix the first comment https://github.com/njgit/App-Pipeline-Lite/commit/274d38255d972f292a2e0c12b747fd5e57e62da9

Have yet to be able to reproduce the issue in the second comment though

**Comment by RGunning** [comment]
I'm still having issues with groupby in a symlink giving a different group order to a groupby in a run command.

I have figured out that the error occurs when there is a previous groupby step in the pipeline with a different groupby condition.

As a minimal example:
test.datasource

    N	filter	group	group2	name
    12	5|6    B	B	james
    16	9|10    A	B	ryan
    15	7|8    B	B	nozomi
    20	12|13	B	B	tiffiny
    20	12|13	C	A	tiffiny
    20	12|13	B	A	tiffiny
    20	12|13	A	A	tiffiny
    20	12|13	B	A	tiffiny
    20	12|13	A	A	tiffiny

test.pipeline

    seq.
	seq [% datasource.N %] | egrep -v '[% datasource.filter %]' > [% seq.filterseq.txt %]

    step2.groupby.group2
        echo [% groupby.group2.datasource.group2 %] > [% step2.cat.txt %];
        cat [% groupby.group2.seq.filterseq.txt %] >> [% step2.cat.txt %]

    step3.groupby.group
	echo [% groupby.group.datasource.group %] > [% step3.cat.txt %];
	cat [% groupby.group.seq.filterseq.txt %] >> [% step3.cat.txt %]


I then run symlink on this with the command `plite symlink -f group -s step3#cat.txt test` 

The $job_ids set by _get_job_ids Lite4.pm#L175 returns 

    $VAR1 = [
          'B',
          'A',
          'C'
        ];

However, the job order set by Resolver.pm#873 and used in the run is

     $VAR1 = [
          'A',
          'B',
          'C'
        ];

Therefore you end up with symlinks pointing to the wrong directory
B points at A
A points at B 
C points at C

**Comment by nw11** [comment]
ok thanks for the test case, will check this out

**Comment by RGunning** [comment]
The pull request does a fix by forcing a sort of the groupby list. Probably not the best way of doing this, but it works
